-- MySQL Script generated by MySQL Workbench
-- 08/09/16 10:29:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lfg_base
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema lfg_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lfg_base` DEFAULT CHARACTER SET utf8 ;
USE `lfg_base` ;

-- -----------------------------------------------------
-- Table `lfg_base`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `email` VARCHAR(128) NOT NULL,
  `password` CHAR(128) NOT NULL,
  `date_joined` DATE NOT NULL,
  `role` ENUM('0', '1') NOT NULL,
  `dob` DATE NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `gender` ENUM('0', '1') NOT NULL,
  `friendship` ENUM('0', '1') NOT NULL,
  `love` ENUM('0', '1') NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`user_location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`user_location` (
  `id_user` INT NOT NULL,
  `ville` VARCHAR(45) NULL,
  `region` VARCHAR(45) NULL,
  `postal_code` INT(10) NULL,
  `country` VARCHAR(45) NULL,
  `lat` FLOAT(10,6) NULL,
  `lng` FLOAT(10,6) NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_city_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_city_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lfg_base`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`user_friendlist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`user_friendlist` (
  `id_friendlist` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_friend` INT NOT NULL,
  `date_added` DATE NOT NULL,
  `statut` ENUM('0', '1', '2', '3') NOT NULL,
  PRIMARY KEY (`id_friendlist`),
  INDEX `fk_friendlist_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_friendlist_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lfg_base`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`photo_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`photo_user` (
  `id_photo` INT NOT NULL,
  `photo_title` VARCHAR(45) NOT NULL,
  `photo_filename` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_photo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`game_all_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`game_all_genre` (
  `id_genre` INT NOT NULL,
  `genre_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_genre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`game` (
  `id_game` INT NOT NULL,
  `game_name` VARCHAR(45) NOT NULL,
  `deck` TEXT(500) NULL,
  `image_url` TEXT(500) NULL,
  `release_date` DATE NULL,
  PRIMARY KEY (`id_game`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`user_genre_fav`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`user_genre_fav` (
  `id_genre_fav` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_genre` INT NOT NULL,
  `date_added` DATE NOT NULL,
  INDEX `fk_user_genre_favori_user1_idx` (`id_user` ASC),
  INDEX `fk_user_genre_favori_genre1_idx` (`id_genre` ASC),
  PRIMARY KEY (`id_genre_fav`),
  CONSTRAINT `fk_user_genre_favori_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lfg_base`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_genre_favori_genre1`
    FOREIGN KEY (`id_genre`)
    REFERENCES `lfg_base`.`game_all_genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`user_game_list`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`user_game_list` (
  `id_game_list` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_game` INT NOT NULL,
  `date_added` DATE NOT NULL,
  PRIMARY KEY (`id_game_list`, `id_user`, `id_game`),
  INDEX `fk_user_has_game_game1_idx` (`id_game` ASC),
  INDEX `fk_user_has_game_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_user_has_game_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lfg_base`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_game_game1`
    FOREIGN KEY (`id_game`)
    REFERENCES `lfg_base`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`photo_gallery_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`photo_gallery_user` (
  `id_photo_gallery` INT NOT NULL AUTO_INCREMENT,
  `id_photo` INT NOT NULL,
  `id_user` INT NOT NULL,
  INDEX `fk_photo_has_user1_user1_idx` (`id_user` ASC),
  INDEX `fk_photo_has_user1_photo1_idx` (`id_photo` ASC),
  PRIMARY KEY (`id_photo_gallery`, `id_photo`, `id_user`),
  CONSTRAINT `fk_photo_has_user1_photo1`
    FOREIGN KEY (`id_photo`)
    REFERENCES `lfg_base`.`photo_user` (`id_photo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_photo_has_user1_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lfg_base`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`user_lovelist`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`user_lovelist` (
  `id_lovelist` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_love` INT NOT NULL,
  `date_added` DATE NOT NULL,
  PRIMARY KEY (`id_lovelist`),
  INDEX `fk_lovelist_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_lovelist_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lfg_base`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`game_genre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`game_genre` (
  `id_game_genre` INT NOT NULL AUTO_INCREMENT,
  `id_genre` INT NOT NULL,
  `id_game` INT NOT NULL,
  PRIMARY KEY (`id_game_genre`, `id_genre`, `id_game`),
  INDEX `fk_game_genre_has_game_game1_idx` (`id_game` ASC),
  INDEX `fk_game_genre_has_game_game_genre1_idx` (`id_genre` ASC),
  CONSTRAINT `fk_game_genre_has_game_game_genre1`
    FOREIGN KEY (`id_genre`)
    REFERENCES `lfg_base`.`game_all_genre` (`id_genre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_genre_has_game_game1`
    FOREIGN KEY (`id_game`)
    REFERENCES `lfg_base`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`game_all_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`game_all_platform` (
  `id_platform` INT NOT NULL AUTO_INCREMENT,
  `platform_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_platform`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`game_platform`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`game_platform` (
  `id_game_platform` INT NOT NULL AUTO_INCREMENT,
  `id_game` INT NOT NULL,
  `iid_platform` INT NOT NULL,
  INDEX `fk_game_has_game_all_platform_game_all_platform1_idx` (`iid_platform` ASC),
  INDEX `fk_game_has_game_all_platform_game1_idx` (`id_game` ASC),
  PRIMARY KEY (`id_game_platform`, `id_game`, `iid_platform`),
  CONSTRAINT `fk_game_has_game_all_platform_game1`
    FOREIGN KEY (`id_game`)
    REFERENCES `lfg_base`.`game` (`id_game`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_has_game_all_platform_game_all_platform1`
    FOREIGN KEY (`iid_platform`)
    REFERENCES `lfg_base`.`game_all_platform` (`id_platform`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lfg_base`.`user_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lfg_base`.`user_info` (
  `id_user` INT NOT NULL,
  `orientation` ENUM('0', '1', '2') NOT NULL,
  `id_battlenet` VARCHAR(45) NULL,
  `id_psn` VARCHAR(45) NULL,
  `id_lol` VARCHAR(45) NULL,
  `id_xbox_live` VARCHAR(45) NULL,
  `id_steam` VARCHAR(45) NULL,
  `description` TEXT(400) NULL,
  PRIMARY KEY (`id_user`),
  INDEX `fk_user_info_user1_idx` (`id_user` ASC),
  CONSTRAINT `fk_user_info_user1`
    FOREIGN KEY (`id_user`)
    REFERENCES `lfg_base`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
